table Table
	lineageTag: 9c7be165-9d9e-43c7-85e1-642976bc0841

	column UPN
		dataType: string
		lineageTag: c3579ad8-aebf-441a-8554-e2edf57a6b15
		summarizeBy: none
		sourceColumn: UPN

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 3fb39050-92d2-46bc-9bf3-c918b9e3a293
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WKklNzHVIzklNzCvOSSxJzUlM0kvOz1XSUXL1dXVUio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [UPN = _t, Region = _t])
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

